# Usa Python oficial
FROM python:3.11-slim

# Evitar que Python guarde .pyc
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instalar dependencias si ya existe requirements.txt
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el proyecto
COPY . /app

# Fly.io expone obligatoriamente el puerto 8080
ENV PORT=8080

# Ejecutar tu app indicando host y puerto obligatorios
CMD ["python", "LyvionTube.py", "--host=0.0.0.0", "--port=8080"]
